export const SCHEMES = [
  {
    id: 1,
    name: 'PM Kisan Samman Nidhi',
    slug: 'pm-kisan-samman-nidhi',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    benefit_type: 'cash',
    benefit_amount: '₹6,000/year',
    benefit_value: 6000,
    description:
      'Direct income support of ₹6,000 per year to small and marginal farmers in 3 installments of ₹2,000 each.',
    eligibility: {
      occupation: ['farmer'],
      income_max: 300000,
      age_min: 18,
      land_required: true,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'Land ownership records (Khasra/Khatauni)',
      'Bank account details',
      'Mobile number linked to Aadhaar',
    ],
    how_to_apply: [
      'Visit pmkisan.gov.in',
      'Click "Farmer Corner" → "New Farmer Registration"',
      'Enter Aadhaar number and state',
      'Fill all details and submit',
      'Verification by local Patwari / Revenue Officer',
    ],
    apply_url: 'https://pmkisan.gov.in',
    is_central: true,
    state: null,
    tags: ['Farmer', 'Direct Benefit', 'Cash Transfer'],
    last_date: null,
  },
  {
    id: 2,
    name: 'PM Awas Yojana (Urban)',
    slug: 'pm-awas-yojana-urban',
    ministry: 'Ministry of Housing and Urban Affairs',
    category: 'Housing',
    benefit_type: 'subsidy',
    benefit_amount: 'Up to ₹2.67 Lakh subsidy',
    benefit_value: 267000,
    description:
      'Credit linked subsidy on home loans for EWS/LIG/MIG households to construct/purchase/renovate their first house.',
    eligibility: {
      occupation: ['any'],
      income_max: 1800000,
      age_min: 18,
      no_pucca_house: true,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'Income certificate',
      'Affidavit of not owning a pucca house',
      'Bank account details',
      'Property documents',
    ],
    how_to_apply: [
      'Visit pmaymis.gov.in',
      'Select "Citizen Assessment"',
      'Choose your benefit type (In Situ/CLSS/AHP/BLC)',
      'Enter Aadhaar and fill the form',
      'Submit and note your application ID',
    ],
    apply_url: 'https://pmaymis.gov.in',
    is_central: true,
    state: null,
    tags: ['Housing', 'Subsidy', 'Home Loan'],
    last_date: null,
  },
  {
    id: 3,
    name: 'PM Mudra Yojana - Tarun',
    slug: 'pm-mudra-yojana-tarun',
    ministry: 'Ministry of Finance',
    category: 'Business/MSME',
    benefit_type: 'loan',
    benefit_amount: 'Loan up to ₹10 Lakh',
    benefit_value: 1000000,
    description:
      'Collateral-free loans for non-corporate small business enterprises. Tarun category: ₹5L-₹10L for established businesses.',
    eligibility: {
      occupation: ['self-employed', 'business'],
      income_max: 10000000,
      age_min: 18,
      age_max: 65,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'PAN Card',
      'Business registration proof',
      'Bank statements (6 months)',
      'Business plan',
      'Passport size photos',
    ],
    how_to_apply: [
      'Visit mudra.org.in',
      'Choose any partner bank/NBFC',
      'Fill Mudra loan application',
      'Submit business plan and documents',
      'Bank processes within 7-30 days',
    ],
    apply_url: 'https://www.mudra.org.in',
    is_central: true,
    state: null,
    tags: ['Business', 'Loan', 'MSME'],
    last_date: null,
  },
  {
    id: 4,
    name: 'Ayushman Bharat - PMJAY',
    slug: 'ayushman-bharat-pmjay',
    ministry: 'Ministry of Health',
    category: 'Healthcare',
    benefit_type: 'insurance',
    benefit_amount: '₹5 Lakh health cover/year',
    benefit_value: 500000,
    description:
      'World\'s largest government health insurance scheme. Free health coverage up to ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    eligibility: {
      occupation: ['any'],
      bpl: true,
      secc_listed: true,
      states: 'all',
      categories: ['SC', 'ST', 'OBC', 'GEN'],
    },
    documents: [
      'Aadhaar Card',
      'Ration Card',
      'SECC database verification',
    ],
    how_to_apply: [
      'Visit pmjay.gov.in to check eligibility',
      'Enter mobile number and Aadhaar',
      'If eligible, go to nearest Ayushman Mitra at empanelled hospital',
      'Get Ayushman Bharat card',
    ],
    apply_url: 'https://pmjay.gov.in',
    is_central: true,
    state: null,
    tags: ['Health', 'Insurance', 'BPL'],
    last_date: null,
  },
  {
    id: 5,
    name: 'National Scholarship Portal - Post Matric',
    slug: 'nsp-post-matric-scholarship',
    ministry: 'Ministry of Social Justice',
    category: 'Education',
    benefit_type: 'scholarship',
    benefit_amount: '₹1,200 - ₹3,000/month',
    benefit_value: 36000,
    description:
      'Scholarship for SC/ST/OBC students studying post-matric or post-secondary courses.',
    eligibility: {
      occupation: ['student'],
      income_max: 250000,
      age_min: 15,
      age_max: 30,
      categories: ['SC', 'ST', 'OBC'],
      states: 'all',
    },
    documents: [
      'Aadhaar Card',
      'Caste Certificate',
      'Income Certificate',
      'Previous year marksheet',
      'Bank account (Aadhaar linked)',
      'Current year admission proof',
    ],
    how_to_apply: [
      'Visit scholarships.gov.in',
      'Register as new student',
      'Select the appropriate scholarship',
      'Fill form and upload documents',
      'Submit before deadline (usually October)',
    ],
    apply_url: 'https://scholarships.gov.in',
    is_central: true,
    state: null,
    tags: ['Student', 'SC/ST/OBC', 'Scholarship'],
    last_date: '31 October 2024',
  },
  {
    id: 6,
    name: 'PM Ujjwala Yojana',
    slug: 'pm-ujjwala-yojana',
    ministry: 'Ministry of Petroleum',
    category: 'Women Welfare',
    benefit_type: 'subsidy',
    benefit_amount: 'Free LPG connection + refill subsidy',
    benefit_value: 1600,
    description:
      'Free LPG gas connections to women from BPL households. Includes free first refill and stove.',
    eligibility: {
      occupation: ['any'],
      gender: ['female'],
      bpl: true,
      age_min: 18,
      categories: ['GEN', 'SC', 'ST', 'OBC'],
      states: 'all',
    },
    documents: [
      'Aadhaar Card',
      'BPL Ration Card',
      'Bank account details',
      'Passport photo',
    ],
    how_to_apply: [
      'Visit nearest LPG distributor (HP/Bharat/Indane)',
      'Fill KYC-5 form',
      'Submit BPL card and Aadhaar',
      'Get connection within 7 days',
    ],
    apply_url: 'https://www.pmujjwalayojana.com',
    is_central: true,
    state: null,
    tags: ['Women', 'BPL', 'LPG', 'Kitchen'],
    last_date: null,
  },
  {
    id: 7,
    name: 'PM Shram Yogi Maan-dhan (PM-SYM)',
    slug: 'pm-shram-yogi-maandhan',
    ministry: 'Ministry of Labour',
    category: 'Senior Citizen',
    benefit_type: 'pension',
    benefit_amount: '₹3,000/month pension after 60',
    benefit_value: 36000,
    description:
      'Voluntary and contributory pension scheme for unorganised sector workers. Monthly pension of ₹3,000 after age 60.',
    eligibility: {
      occupation: ['unorganised-worker', 'daily-wage', 'street-vendor', 'farmer'],
      income_max: 180000,
      age_min: 18,
      age_max: 40,
      epf_not_member: true,
      categories: ['GEN', 'SC', 'ST', 'OBC'],
      states: 'all',
    },
    documents: [
      'Aadhaar Card',
      'Savings bank account / Jan Dhan account',
      'Mobile number',
    ],
    how_to_apply: [
      'Visit maandhan.in',
      'Click "Self Enrollment"',
      'Enter mobile number and Aadhaar',
      'Choose monthly contribution amount (₹55-₹200)',
      'Set up auto-debit from bank',
    ],
    apply_url: 'https://maandhan.in',
    is_central: true,
    state: null,
    tags: ['Pension', 'Unorganised Workers', 'Retirement'],
    last_date: null,
  },
  {
    id: 8,
    name: 'Stand-Up India',
    slug: 'stand-up-india',
    ministry: 'Ministry of Finance',
    category: 'Business/MSME',
    benefit_type: 'loan',
    benefit_amount: '₹10 Lakh - ₹1 Crore loan',
    benefit_value: 10000000,
    description:
      'Bank loans between ₹10 lakh and ₹1 crore to SC/ST and women entrepreneurs for setting up greenfield enterprises.',
    eligibility: {
      occupation: ['business', 'self-employed'],
      gender_or_category: true,
      gender: ['female'],
      categories: ['SC', 'ST'],
      age_min: 18,
      greenfield_only: true,
      states: 'all',
    },
    documents: [
      'Aadhaar Card',
      'PAN Card',
      'Caste certificate (for SC/ST)',
      'Business plan',
      'Property documents (if any)',
      'Bank statements',
    ],
    how_to_apply: [
      'Visit standupmitra.in',
      'Register and fill the application',
      'Choose preferred bank',
      'Submit business plan',
      'Bank reviews and sanctions within 90 days',
    ],
    apply_url: 'https://www.standupmitra.in',
    is_central: true,
    state: null,
    tags: ['Women', 'SC/ST', 'Loan', 'Business'],
    last_date: null,
  },
  {
    id: 9,
    name: 'Sukanya Samriddhi Yojana',
    slug: 'sukanya-samriddhi-yojana',
    ministry: 'Ministry of Finance',
    category: 'Women Welfare',
    benefit_type: 'savings',
    benefit_amount: '8.2% interest + tax benefits',
    benefit_value: 82000,
    description:
      'Small savings scheme for girl child. Account can be opened for girls up to 10 years old. Matures after 21 years.',
    eligibility: {
      gender: ['female'],
      age_min: 0,
      age_max: 10,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Birth certificate of girl child',
      'Parent/guardian Aadhaar',
      'Parent/guardian PAN',
    ],
    how_to_apply: [
      'Visit any Post Office or authorized bank',
      'Fill SSY account opening form',
      'Submit documents',
      'Minimum deposit ₹250',
      'Account opened same day',
    ],
    apply_url: 'https://www.indiapost.gov.in',
    is_central: true,
    state: null,
    tags: ['Girl Child', 'Savings', 'Tax Benefit'],
    last_date: null,
  },
  {
    id: 10,
    name: 'PM Jan Dhan Yojana',
    slug: 'pm-jan-dhan-yojana',
    ministry: 'Ministry of Finance',
    category: 'Employment',
    benefit_type: 'bank-account',
    benefit_amount: '₹10,000 overdraft + ₹2L insurance',
    benefit_value: 210000,
    description:
      'Zero-balance bank accounts with ₹10,000 overdraft facility, ₹2L accident insurance, and RuPay debit card.',
    eligibility: {
      occupation: ['any'],
      no_bank_account: true,
      age_min: 10,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'Passport photo',
      'Address proof (if different from Aadhaar)',
    ],
    how_to_apply: [
      'Visit any bank branch or Bank Mitra',
      'Fill account opening form',
      'Submit Aadhaar and photo',
      'Account opened same day',
      'Get RuPay card within 10 days',
    ],
    apply_url: 'https://pmjdy.gov.in',
    is_central: true,
    state: null,
    tags: ['Bank Account', 'Insurance', 'Zero Balance'],
    last_date: null,
  },
  {
    id: 11,
    name: 'Kisan Credit Card (KCC)',
    slug: 'kisan-credit-card',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    benefit_type: 'credit',
    benefit_amount: 'Crop loan up to ₹3 Lakh @ 4% interest',
    benefit_value: 300000,
    description:
      'Short-term credit for crop cultivation, allied activities, and non-farm income. Interest subvention brings effective rate to 4%.',
    eligibility: {
      occupation: ['farmer'],
      age_min: 18,
      age_max: 75,
      land_required: true,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'Land records',
      'Passport photo',
      'Bank account',
    ],
    how_to_apply: [
      'Visit nearest cooperative/commercial bank',
      'Fill KCC application form',
      'Submit land records and Aadhaar',
      'Bank verifies and approves within 14 days',
    ],
    apply_url: 'https://fasalrin.gov.in',
    is_central: true,
    state: null,
    tags: ['Farmer', 'Crop Loan', 'Low Interest'],
    last_date: null,
  },
  {
    id: 12,
    name: 'PM SVANidhi - Street Vendor Loan',
    slug: 'pm-svanidhi',
    ministry: 'Ministry of Housing',
    category: 'Business/MSME',
    benefit_type: 'loan',
    benefit_amount: '₹10,000 → ₹20,000 → ₹50,000 loan',
    benefit_value: 50000,
    description:
      'Affordable working capital loan for street vendors. Start with ₹10,000, scale up to ₹50,000 with timely repayment.',
    eligibility: {
      occupation: ['street-vendor', 'self-employed'],
      vending_certificate: true,
      age_min: 18,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: [
      'Aadhaar Card',
      'Vending certificate / letter of recommendation from ULB',
      'Bank account',
    ],
    how_to_apply: [
      'Visit pmsvanidhi.mohua.gov.in',
      'Apply online or via Town Vending Committee',
      'Submit documents',
      'Loan sanctioned within 30 days',
    ],
    apply_url: 'https://pmsvanidhi.mohua.gov.in',
    is_central: true,
    state: null,
    tags: ['Street Vendor', 'Micro Loan', 'Urban Poor'],
    last_date: null,
  },
  {
    id: 13,
    name: 'Beti Bachao Beti Padhao',
    slug: 'beti-bachao-beti-padhao',
    ministry: 'Ministry of Women & Child Development',
    category: 'Women Welfare',
    benefit_type: 'awareness+cash',
    benefit_amount: 'Cash incentives + education support',
    benefit_value: 20000,
    description:
      'Scheme to address declining child sex ratio and promote girl child education. Cash incentives for educating girl children.',
    eligibility: {
      gender: ['female'],
      age_min: 0,
      age_max: 10,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Birth certificate', 'Parent Aadhaar', 'School enrollment proof'],
    how_to_apply: ['Contact district WCD office', 'Fill application form', 'Submit documents'],
    apply_url: 'https://wcd.nic.in',
    is_central: true,
    state: null,
    tags: ['Girl Child', 'Education', 'Women'],
    last_date: null,
  },
  {
    id: 14,
    name: 'PM Fasal Bima Yojana',
    slug: 'pm-fasal-bima-yojana',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    benefit_type: 'insurance',
    benefit_amount: 'Crop loss compensation at low premium',
    benefit_value: 100000,
    description:
      'Crop insurance at just 1.5-2% premium for Kharif/Rabi crops. Protects farmers from crop losses due to natural calamities.',
    eligibility: {
      occupation: ['farmer'],
      age_min: 18,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Land records', 'Bank account', 'Sowing certificate'],
    how_to_apply: [
      'Apply via pmfby.gov.in or nearest bank/CSC',
      'Enroll within crop season deadline',
      'Pay nominal premium',
    ],
    apply_url: 'https://pmfby.gov.in',
    is_central: true,
    state: null,
    tags: ['Farmer', 'Crop Insurance', 'Natural Disaster'],
    last_date: null,
  },
  {
    id: 15,
    name: 'Atal Pension Yojana',
    slug: 'atal-pension-yojana',
    ministry: 'Ministry of Finance',
    category: 'Senior Citizen',
    benefit_type: 'pension',
    benefit_amount: '₹1,000 - ₹5,000/month pension',
    benefit_value: 60000,
    description:
      'Guaranteed pension of ₹1,000-₹5,000/month for unorganised sector workers after age 60. Government co-contributes 50%.',
    eligibility: {
      occupation: ['any'],
      age_min: 18,
      age_max: 40,
      bank_account: true,
      not_income_tax_payer: true,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Bank account', 'Mobile number'],
    how_to_apply: [
      'Visit any bank or post office',
      'Fill APY registration form',
      'Link to savings account',
      'Choose pension amount',
    ],
    apply_url: 'https://npscra.nsdl.co.in',
    is_central: true,
    state: null,
    tags: ['Pension', 'Retirement', 'Low Income'],
    last_date: null,
  },
  {
    id: 16,
    name: 'PM Vishwakarma Yojana',
    slug: 'pm-vishwakarma-yojana',
    ministry: 'Ministry of MSME',
    category: 'Business/MSME',
    benefit_type: 'training+loan',
    benefit_amount: '₹15,000 toolkit + ₹3L loan @ 5%',
    benefit_value: 315000,
    description:
      'Support for traditional artisans and craftspeople (18 trades). Includes recognition, skill training, toolkit grant, and collateral-free loans.',
    eligibility: {
      occupation: ['artisan', 'craftsman', 'self-employed'],
      trades: ['carpenter', 'tailor', 'blacksmith', 'potter', 'weaver', 'cobbler'],
      age_min: 18,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Caste certificate', 'Proof of trade practice'],
    how_to_apply: [
      'Visit pmvishwakarma.gov.in',
      'Register as artisan',
      'Verify at nearest CSC',
      'Enroll for skill training',
      'Get PM Vishwakarma certificate and ID card',
    ],
    apply_url: 'https://pmvishwakarma.gov.in',
    is_central: true,
    state: null,
    tags: ['Artisan', 'Craftsman', 'Skill', 'Loan'],
    last_date: null,
  },
  {
    id: 17,
    name: 'PM Jan Arogya Yojana (SEHAT)',
    slug: 'sehat-health-insurance',
    ministry: 'Ministry of Health',
    category: 'Healthcare',
    benefit_type: 'insurance',
    benefit_amount: '₹5 Lakh health cover',
    benefit_value: 500000,
    description: 'Extended Ayushman Bharat coverage to all residents of J&K and other UTs.',
    eligibility: {
      states: ['Jammu & Kashmir', 'Ladakh'],
      age_min: 0,
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Residence certificate'],
    how_to_apply: ['Visit nearest Jan Aushadhi kendra', 'Get SEHAT card'],
    apply_url: 'https://pmjay.gov.in',
    is_central: true,
    state: null,
    tags: ['Health', 'Insurance', 'J&K'],
    last_date: null,
  },
  {
    id: 18,
    name: 'National Rural Livelihood Mission (NRLM)',
    slug: 'national-rural-livelihood-mission',
    ministry: 'Ministry of Rural Development',
    category: 'Employment',
    benefit_type: 'training+loan',
    benefit_amount: '₹1.1-₹6 Lakh revolving fund',
    benefit_value: 600000,
    description:
      'Mobilizes rural poor women into SHGs, provides skill training, revolving fund, and bank linkage for livelihood improvement.',
    eligibility: {
      gender: ['female'],
      occupation: ['any'],
      rural: true,
      age_min: 18,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'SHG membership certificate', 'Bank account'],
    how_to_apply: [
      'Contact nearest Block Development Office',
      'Join or form a Self Help Group',
      'Get SHG registered with NRLM',
      'Access revolving fund and bank linkage',
    ],
    apply_url: 'https://aajeevika.gov.in',
    is_central: true,
    state: null,
    tags: ['Women', 'SHG', 'Rural', 'Employment'],
    last_date: null,
  },
  {
    id: 19,
    name: 'PMEGP - Manufacturing Subsidy',
    slug: 'pmegp-manufacturing-subsidy',
    ministry: 'Ministry of MSME',
    category: 'Business/MSME',
    benefit_type: 'subsidy',
    benefit_amount: '15-35% subsidy on project cost',
    benefit_value: 2500000,
    description:
      'Margin money subsidy of 15-35% for setting up micro enterprises in manufacturing or service sector.',
    eligibility: {
      occupation: ['self-employed', 'business'],
      age_min: 18,
      education_min: '8th pass',
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Educational certificate', 'Project report', 'Bank loan sanction letter'],
    how_to_apply: [
      'Apply at kviconline.gov.in',
      'Choose KVIC/KVIB/DIC channel',
      'Submit project report',
      'Get bank loan sanctioned',
      'Subsidy credited after 3 years',
    ],
    apply_url: 'https://kviconline.gov.in/pmegpeportal',
    is_central: true,
    state: null,
    tags: ['Manufacturing', 'Subsidy', 'Self Employment'],
    last_date: null,
  },
  {
    id: 20,
    name: 'PM Kisan Maandhan Yojana',
    slug: 'pm-kisan-maandhan-yojana',
    ministry: 'Ministry of Agriculture',
    category: 'Agriculture',
    benefit_type: 'pension',
    benefit_amount: '₹3,000/month pension after 60',
    benefit_value: 36000,
    description:
      'Pension scheme for small and marginal farmers. Monthly contribution of ₹55-₹200 matched by government. ₹3,000/month after 60.',
    eligibility: {
      occupation: ['farmer'],
      income_max: 300000,
      age_min: 18,
      age_max: 40,
      land_max: 2,
      states: 'all',
      categories: ['GEN', 'SC', 'ST', 'OBC'],
    },
    documents: ['Aadhaar', 'Land records', 'Bank account', 'Mobile number'],
    how_to_apply: [
      'Visit maandhan.in or nearest CSC',
      'Self-enroll or CSC operator enrolls',
      'Set auto-debit from PM Kisan installment',
    ],
    apply_url: 'https://maandhan.in',
    is_central: true,
    state: null,
    tags: ['Farmer', 'Pension', 'Old Age'],
    last_date: null,
  },
];

export const CATEGORIES = [
  { id: 1, name: 'Agriculture', icon: '🌾', slug: 'agriculture', count: 284 },
  { id: 2, name: 'Education', icon: '📚', slug: 'education', count: 198 },
  { id: 3, name: 'Housing', icon: '🏠', slug: 'housing', count: 87 },
  { id: 4, name: 'Employment', icon: '💼', slug: 'employment', count: 156 },
  { id: 5, name: 'Women Welfare', icon: '👩', slug: 'women-welfare', count: 142 },
  { id: 6, name: 'Healthcare', icon: '🏥', slug: 'healthcare', count: 119 },
  { id: 7, name: 'Business/MSME', icon: '💰', slug: 'business-msme', count: 93 },
  { id: 8, name: 'Senior Citizen', icon: '👴', slug: 'senior-citizen', count: 67 },
  { id: 9, name: 'Child Care', icon: '👶', slug: 'child-care', count: 78 },
  { id: 10, name: 'Disability', icon: '♿', slug: 'disability', count: 45 },
  { id: 11, name: 'Energy/Solar', icon: '⚡', slug: 'energy-solar', count: 38 },
  { id: 12, name: 'Animal Husbandry', icon: '🐄', slug: 'animal-husbandry', count: 56 },
];

export const STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Jammu & Kashmir', 'Ladakh', 'Puducherry', 'Chandigarh',
];

export const OCCUPATIONS = [
  { value: 'farmer', label: 'Farmer / Agriculture' },
  { value: 'student', label: 'Student' },
  { value: 'salaried', label: 'Salaried Employee' },
  { value: 'self-employed', label: 'Self Employed' },
  { value: 'business', label: 'Business Owner' },
  { value: 'unemployed', label: 'Unemployed' },
  { value: 'daily-wage', label: 'Daily Wage Worker' },
  { value: 'street-vendor', label: 'Street Vendor' },
  { value: 'artisan', label: 'Artisan / Craftsman' },
  { value: 'unorganised-worker', label: 'Unorganised Sector Worker' },
  { value: 'homemaker', label: 'Homemaker' },
];
